name: Develop in Branch
on: [pull_request, workflow_dispatch]
jobs:
  job1:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - run: |
        echo "Workflow triggered by event: ${{ github.event_name }}"
        echo "Workflow triggered by actor: ${{ github.actor }}"
    - uses: actions/checkout@v6
    - uses: devops-actions/actionlint@v0.1.11